"""Load a simple JSON note chart used for timing analysis.

The chart format is intentionally simple (not simai/maidata) so it can be
authored by hand or generated by another tool:

    [
      {"time": 1.234, "hand": "left", "label": "tap"},
      {"time": 1.482, "hand": "right"}
    ]

``hand`` is one of "left", "right", or "either" (default "either").
"""
import json
from dataclasses import dataclass


@dataclass
class Note:
    time_sec: float
    hand: str = "either"
    label: str = ""


def load_chart(path: str) -> list[Note]:
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    notes = [
        Note(
            time_sec=float(n["time"]),
            hand=n.get("hand", "either"),
            label=n.get("label", ""),
        )
        for n in data
    ]
    notes.sort(key=lambda n: n.time_sec)
    return notes
